name: Bangalore Traffic Snapshot

on:
  schedule:
    - cron: "10 * * * *"
  workflow_dispatch: {}

jobs:
  snapshot:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: blr-traffic-monitor

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run traffic snapshot (headless Chrome)
        run: |
          export LC_ALL=en_US.UTF-8
          export LANG=en_US.UTF-8
          python traffic_snapshot.py

      - name: Commit results
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add csv-bangalore_traffic_raw.csv csv-bangalore_traffic_processed.csv || true
          git commit -m "traffic: hourly snapshot [skip ci]" || echo "No changes"
          git push || true
