name: Bangalore Traffic Snapshot

on:
  schedule:
    - cron: "10 * * * *"
      timezone: Asia/Kolkata
  workflow_dispatch: {}

jobs:
  snapshot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v2
        with:
          version: "3.13"

      - name: Create venv
        run: uv venv .venv
        
      - name: Install dependencies
        run: uv pip install -r requirements.txt

      - name: Run traffic snapshot (headless Chrome)
        id: snapshot
        run: |
          export LC_ALL=en_US.UTF-8
          export LANG=en_US.UTF-8
          message="$(python traffic_snapshot.py | tail -n1)"
          echo "$message"
          echo "message=$message" >> "$GITHUB_OUTPUT"

      - name: Commit results
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add csv-bangalore_traffic_raw.csv csv-bangalore_traffic_processed.csv || true
          git commit -m "${{ steps.snapshot.outputs.message }}" || echo "No changes"
          git push || true
