name: Bangalore Traffic Snapshot
on:
  schedule:
    - cron: "45 * * * *"   # primary (HH:15 IST)
    - cron: "46 * * * *"   # fallback (HH:16 IST)
  workflow_dispatch: {}

concurrency:
  group: traffic-snapshot
  cancel-in-progress: false

jobs:
  snapshot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v2
        with:
          version: latest

      - name: Cache uv venv
        uses: actions/cache@v4
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            venv-${{ runner.os }}-

      - name: Create venv (idempotent)
        run: uv venv .venv

      - name: Install dependencies (using uv in venv)
        run: uv pip install -r requirements.txt --python .venv/bin/python

      - name: Run and capture snapshot message
        id: snapshot
        run: |
          export LC_ALL=en_US.UTF-8
          export LANG=en_US.UTF-8
          message="$(.venv/bin/python traffic_snapshot.py | tail -n1)"
          echo "$message"
          echo "message=$message" >> "$GITHUB_OUTPUT"

      - name: Deduplicate CSV and commit
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          # Dedup by (date,time,route_code)
          tmpfile=$(mktemp)
          awk -F, '!seen[$1 FS $2 FS $3]++' csv-bangalore_traffic.csv > "$tmpfile" && mv "$tmpfile" csv-bangalore_traffic.csv
          git add csv-bangalore_traffic.csv || true
          git commit -m "${{ steps.snapshot.outputs.message }}" || echo "No changes"
          git push || true
